## Positional Imports

In [1]:
import pandas as pd
import sys
sys.path.extend(['./extras', './weekly', './models', './utils'])
import exp
from injuries import get_injuries_for_all_teams
from salary import get_salaries

In [2]:
final_dfs = []

### Read Previous Data

In [3]:
f_before_2024 = pd.read_pickle('pickles/f_before_2024.pickle')
f_before_2024.rename(columns={'Team': 'team'}, inplace=True)
f_2024 = pd.read_pickle('pickles/f_2024.pickle')
f_2024.rename(columns={'Team': 'team'}, inplace=True)
f_before_2024.drop(columns='Coach', inplace=True)
f_2024.drop(columns='Coach', inplace=True)
duplicates = f_2024[f_2024.duplicated(subset=['year', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [year, week, team, G-season, W-season, L-season, T-season, G-w/team, W-w/team, L-w/team, T-w/team, G-career, W-career, L-career, T-career, G plyf-playoffs, W plyf-playoffs, L plyf-playoffs, G plyf-w/team, W plyf-w/team, L plyf-w/team, G plyf-career, W plyf-career, L plyf-career, Remark, w/same_team, Gms-fds, Rush-fds, Pass-fds, Pen-fds, Pct-tde, Pct-fde, gameday, weekday, gametime, away_team, home_team, away_moneyline, home_moneyline, spread_line, away_spread_odds, home_spread_odds, total_line, under_odds, over_odds, div_game, roof, surface, temp, wind, referee, stadium, bye_week, oline_rank, dline_rank]
Index: []

[0 rows x 55 columns]

### Retrieve Position Info

In [4]:
# d1 = get_indiv(2024, 'RB')
# d2 = get_indiv(2023, 'RB')
# d3 = get_indiv(2022, 'RB')
# d4 = get_indiv(2021, 'RB')
# d1 = cum_adjust(d1, [d4, d3, d2])
# d1.to_pickle('pickles/rb_2024.pickle')
# d2 = d2 = cum_adjust(d2, [d4, d3])
# d2.to_pickle('pickles/rb_before_2024.pickle')

# exp_obj = Exp()
# df, past_df = exp_obj.get_all(2024, 'K')
# past_df.to_pickle('pickles/k_before_2024.pickle')
# df.to_pickle('pickles/k_2024.pickle')

# inj_before_2024 = pd.concat([get_injuries_for_all_teams(year, 'K') for year in range(2022, 2024)], ignore_index=True)
# inj_before_2024.to_pickle('pickles/k_inj_before_2024.pickle')
# inj_2024 = get_injuries_for_all_teams(2024, 'K')
# inj_2024.to_pickle('pickles/k_inj_2024.pickle')

# pos_salaries = get_salaries('K')
# pos_salaries.to_pickle('pickles/k_salaries.pickle')

# 1. Quarterbacks

In [5]:
qb_before_2024 = pd.read_pickle('pickles/qb_before_2024.pickle')
qb_2024 = pd.read_pickle('pickles/qb_2024.pickle')

In [6]:
qb_before_2024 = pd.read_pickle('pickles/qb_before_2024.pickle')
qb_2024 = pd.read_pickle('pickles/qb_2024.pickle')
duplicates = qb_before_2024[qb_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points]
Index: []

[0 rows x 86 columns]

In [7]:
duplicates = qb_2024[qb_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points]
Index: []

[0 rows x 86 columns]

In [8]:
qb_exp_before_2024 = pd.read_pickle('pickles/qb_exp_before_2024.pickle')
qb_exp_2024 = pd.read_pickle('pickles/qb_exp_2024.pickle')
duplicates = qb_exp_before_2024[qb_exp_before_2024.duplicated(subset=['year', 'player_name', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [year, player_name, team, age, len_with_team]
Index: []

In [9]:
duplicates = qb_exp_2024[qb_exp_2024.duplicated(subset=['year', 'player_name', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [year, player_name, team, age, len_with_team]
Index: []

In [10]:
qb_inj_before_2024 = pd.read_pickle('pickles/qb_inj_before_2024.pickle')
qb_inj_2024 = pd.read_pickle('pickles/qb_inj_2024.pickle')
duplicates = qb_inj_before_2024[qb_inj_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [year, week, team, player_name, Injury, Wed, Thu, Fri, Game Status]
Index: []

In [11]:
duplicates = qb_inj_2024[qb_inj_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [year, week, team, player_name, Injury, Wed, Thu, Fri, Game Status]
Index: []

In [12]:
qb_sal = pd.read_pickle('pickles/qb_salaries.pickle')
duplicates = qb_sal[qb_sal.duplicated(subset=['player_name', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [player_name, team, Total Value, APY, Total Guaranteed, Avg. Guarantee/Year, % Guaranteed]
Index: []

### Using team val from og qb dfs, drop others

In [13]:
qb_exp_before_2024 = qb_exp_before_2024.drop(columns=['team'])
qb_exp_2024 = qb_exp_2024.drop(columns=['team'])
qb_inj_before_2024 = qb_inj_before_2024.drop(columns=['team'])
qb_inj_2024 = qb_inj_2024.drop(columns=['team'])
qb_sal = qb_sal.drop(columns=['team'])

### Merge qb and exp

In [14]:
qb_before_2024 = qb_before_2024.merge(qb_exp_before_2024, on=['year', 'player_name'], how='left')
qb_2024 = qb_2024.merge(qb_exp_2024, on=['year', 'player_name'], how='left')

In [15]:
qb_before_2024[qb_before_2024.isna().any(axis=1)]

,week,player_name,opponent_team,team,year,points,depth_team,prev_completions,prev_attempts,prev_passing_yards,...,cum_receiving_first_downs,cum_receiving_epa,cum_receiving_2pt_conversions,cum_racr,cum_target_share,cum_air_yards_share,cum_wopr,cum_points,age,len_with_team
514,6,P.J. Walker,1,17,2023,3.78,1,99,172,1093.0,...,0,0.0,0,0,0.0,0.0,0.0,0.00,NaN,NaN
515,7,P.J. Walker,18,17,2023,5.42,2,99,172,1093.0,...,0,0.0,0,0,0.0,0.0,0.0,3.78,NaN,NaN
516,8,P.J. Walker,22,17,2023,10.62,3,99,172,1093.0,...,0,0.0,0,0,0.0,0.0,0.0,9.20,NaN,NaN
517,10,P.J. Walker,6,17,2023,0.00,2,99,172,1093.0,...,0,0.0,0,0,0.0,0.0,0.0,19.82,NaN,NaN
518,12,P.J. Walker,23,17,2023,0.14,2,99,172,1093.0,...,0,0.0,0,0,0.0,0.0,0.0,19.82,NaN,NaN

In [16]:
qb_before_2024 = qb_before_2024.dropna()

In [17]:
qb_before_2024[qb_before_2024.isna().any(axis=1)]

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team]
Index: []

[0 rows x 88 columns]

In [18]:
qb_2024[qb_2024.isna().any(axis=1)]

,week,player_name,opponent_team,team,year,points,depth_team,prev_completions,prev_attempts,prev_passing_yards,...,cum_receiving_first_downs,cum_receiving_epa,cum_receiving_2pt_conversions,cum_racr,cum_target_share,cum_air_yards_share,cum_wopr,cum_points,age,len_with_team
380,18,Joe Milton,2,30,2024,19.24,3,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,0.0,0.00,NaN,NaN
559,7,Michael Penix,22,16,2024,0.56,2,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,0.0,0.00,NaN,NaN
560,11,Michael Penix,23,16,2024,0.96,2,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,0.0,0.56,NaN,NaN
561,16,Michael Penix,29,16,2024,6.38,2,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,0.0,1.52,NaN,NaN
562,17,Michael Penix,20,16,2024,11.22,2,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,0.0,7.90,NaN,NaN
563,18,Michael Penix,26,16,2024,24.98,1,0,0,0.0,...,0,0.0,0,0.0,0.0,0.0,0.0,19.12,NaN,NaN

In [19]:
qb_2024.loc[qb_2024['player_name'] == 'Joe Milton', ['age', 'len_with_team']] = [24, 1]
qb_2024.loc[qb_2024['player_name'] == 'Michael Penix', ['age', 'len_with_team']] = [24, 1]
qb_2024[qb_2024.isna().any(axis=1)]

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team]
Index: []

[0 rows x 88 columns]

In [20]:
duplicates = qb_before_2024[qb_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
print(duplicates)
duplicates = qb_2024[qb_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team]
Index: []

[0 rows x 88 columns]

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team]
Index: []

[0 rows x 88 columns]

### Merge qb with injuries

In [21]:
qb_before_2024 = qb_before_2024.merge(qb_inj_before_2024, on=['year', 'week', 'player_name'], how='left')
qb_2024 = qb_2024.merge(qb_inj_2024, on=['year', 'week', 'player_name'], how='left')

In [22]:
qb_before_2024[qb_before_2024.isna().any(axis=1)]

,week,player_name,opponent_team,team,year,points,depth_team,prev_completions,prev_attempts,prev_passing_yards,...,cum_air_yards_share,cum_wopr,cum_points,age,len_with_team,Injury,Wed,Thu,Fri,Game Status
0,14,AJ McCarron,18,14,2023,-0.04,2,0,0,0.0,...,0.0,0.0,0.000000,32.0,1.0,NaN,NaN,NaN,NaN,NaN
1,18,AJ McCarron,17,14,2023,0.80,2,0,0,0.0,...,0.0,0.0,-0.040000,32.0,1.0,NaN,NaN,NaN,NaN,NaN
2,1,Aaron Rodgers,2,31,2023,0.00,1,736,1102,8035.0,...,0.0,0.0,0.000000,39.0,1.0,NaN,NaN,NaN,NaN,NaN
3,4,Aidan O'Connell,21,27,2023,9.82,3,0,0,0.0,...,0.0,0.0,0.000000,24.0,1.0,NaN,NaN,NaN,NaN,NaN
4,7,Aidan O'Connell,19,27,2023,5.00,3,0,0,0.0,...,0.0,0.0,9.820000,24.0,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
680,8,Zach Wilson,29,31,2023,12.10,1,345,625,4022.0,...,0.0,0.0,61.680000,24.0,3.0,NaN,NaN,NaN,NaN,NaN
681,9,Zach Wilson,21,31,2023,7.22,1,345,625,4022.0,...,0.0,0.0,73.780001,24.0,3.0,NaN,NaN,NaN,NaN,NaN
682,10,Zach Wilson,27,31,2023,13.92,1,345,625,4022.0,...,0.0,0.0,81.000000,24.0,3.0,NaN,NaN,NaN,NaN,NaN
683,11,Zach Wilson,2,31,2023,6.74,1,345,625,4022.0,...,0.0,0.0,94.920001,24.0,3.0,NaN,NaN,NaN,NaN,NaN
684,14,Zach Wilson,15,31,2023,19.24,3,345,625,4022.0,...,0.0,0.0,101.660000,24.0,3.0,NaN,NaN,NaN,NaN,NaN

In [23]:
qb_before_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']] = qb_before_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']].fillna(0)

In [24]:
qb_before_2024[qb_before_2024.isna().any(axis=1)]

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status]
Index: []

[0 rows x 93 columns]

In [25]:
qb_2024[qb_2024.isna().any(axis=1)]

,week,player_name,opponent_team,team,year,points,depth_team,prev_completions,prev_attempts,prev_passing_yards,...,cum_air_yards_share,cum_wopr,cum_points,age,len_with_team,Injury,Wed,Thu,Fri,Game Status
0,1,Aaron Rodgers,1,31,2024,8.580000,1,736,1103,8035.0,...,0.0,0.0,0.000000,40.0,2.0,NaN,NaN,NaN,NaN,NaN
1,2,Aaron Rodgers,25,31,2024,15.140000,1,736,1103,8035.0,...,0.0,0.0,8.580000,40.0,2.0,NaN,NaN,NaN,NaN,NaN
2,3,Aaron Rodgers,30,31,2024,21.040001,1,736,1103,8035.0,...,0.0,0.0,23.720000,40.0,2.0,NaN,NaN,NaN,NaN,NaN
3,4,Aaron Rodgers,23,31,2024,11.600000,1,736,1103,8035.0,...,0.0,0.0,44.760001,40.0,2.0,NaN,NaN,NaN,NaN,NaN
11,13,Aaron Rodgers,22,31,2024,14.000000,1,736,1103,8035.0,...,0.0,0.0,156.680001,40.0,2.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,11,Will Levis,9,25,2024,15.600000,3,149,255,1808.0,...,0.0,0.0,57.660000,25.0,2.0,NaN,NaN,NaN,NaN,NaN
692,12,Will Levis,15,25,2024,16.120001,3,149,255,1808.0,...,0.0,0.0,73.260001,25.0,2.0,NaN,NaN,NaN,NaN,NaN
693,13,Will Levis,20,25,2024,16.180000,3,149,255,1808.0,...,0.0,0.0,89.380002,25.0,2.0,NaN,NaN,NaN,NaN,NaN
694,14,Will Levis,12,25,2024,7.020000,1,149,255,1808.0,...,0.0,0.0,105.560002,25.0,2.0,NaN,NaN,NaN,NaN,NaN
696,18,Will Levis,15,25,2024,11.800000,2,149,255,1808.0,...,0.0,0.0,108.140002,25.0,2.0,NaN,NaN,NaN,NaN,NaN

In [26]:
qb_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']] = qb_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']].fillna(0)
qb_2024[qb_2024.isna().any(axis=1)]

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status]
Index: []

[0 rows x 93 columns]

In [27]:
duplicates = qb_before_2024[qb_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
print(duplicates)
duplicates = qb_2024[qb_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False)]
duplicates

    week     player_name  opponent_team  team  year     points depth_team  \
31     2  Baker Mayfield             19    24  2023  18.379999          1
32     2  Baker Mayfield             19    24  2023  18.379999          1

    prev_completions  prev_attempts  prev_passing_yards  ...  \
31               454            753              5173.0  ...
32               454            753              5173.0  ...

    cum_air_yards_share  cum_wopr  cum_points   age  len_with_team  Injury  \
31                  0.0       0.0       16.02  28.0            1.0    23.0
32                  0.0       0.0       16.02  28.0            1.0    48.0

    Wed  Thu  Fri  Game Status
31  1.0  1.0  1.0          1.0
32  1.0  1.0  1.0          1.0

[2 rows x 93 columns]

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status]
Index: []

[0 rows x 93 columns]

In [28]:
qb_before_2024 = qb_before_2024.drop(index=32)
duplicates = qb_before_2024[qb_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status]
Index: []

[0 rows x 93 columns]

### Merge qb with sal

In [29]:
qb_before_2024 = qb_before_2024.merge(qb_sal, on=['player_name'], how='left')
qb_2024 = qb_2024.merge(qb_sal, on=['player_name'], how='left')

In [30]:
duplicates = qb_before_2024[qb_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
print(duplicates)
duplicates = qb_2024[qb_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status, Total Value, APY, Total Guaranteed, Avg. Guarantee/Year, % Guaranteed]
Index: []

[0 rows x 98 columns]

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status, Total Value, APY, Total Guaranteed, Avg. Guarantee/Year, % Guaranteed]
Index: []

[0 rows x 98 columns]

In [31]:
print(qb_before_2024.isna().any().any())
print(qb_2024.isna().any().any())

True
True

In [32]:
cols = ['Total Value', 'APY', 'Total Guaranteed', 'Avg. Guarantee/Year', '% Guaranteed']
for df in [qb_before_2024, qb_2024]:
    for col in cols:
        df[col].fillna(df[col].mean(), inplace=True)

In [33]:
print(qb_before_2024.isna().any().any())
print(qb_2024.isna().any().any())

False
False

### Merge with previous data

In [34]:
qb_before_2024 = qb_before_2024.merge(f_before_2024, on=['year', 'week', 'team'], how='left')
qb_2024 = qb_2024.merge(f_2024, on=['year', 'week', 'team'], how='left')

In [35]:
print(qb_before_2024.isna().any().any())
print(qb_2024.isna().any().any())

False
False

In [36]:
duplicates = qb_before_2024[qb_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status, Total Value, APY, Total Guaranteed, Avg. Guarantee/Year, % Guaranteed, G-season, W-season, ...]
Index: []

[0 rows x 150 columns]

In [37]:
duplicates = qb_2024[qb_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status, Total Value, APY, Total Guaranteed, Avg. Guarantee/Year, % Guaranteed, G-season, W-season, ...]
Index: []

[0 rows x 150 columns]

### Add to final_dfs

In [38]:
final_dfs.append([qb_before_2024, qb_2024])

# 2. Running Backs

In [39]:
rb_before_2024 = pd.read_pickle('pickles/rb_before_2024.pickle')
rb_2024 = pd.read_pickle('pickles/rb_2024.pickle')
duplicates = rb_before_2024[rb_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points]
Index: []

[0 rows x 86 columns]

In [40]:
duplicates = rb_2024[rb_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points]
Index: []

[0 rows x 86 columns]

In [41]:
rb_exp_before_2024 = pd.read_pickle('pickles/rb_exp_before_2024.pickle')
rb_exp_2024 = pd.read_pickle('pickles/rb_exp_2024.pickle')
duplicates = rb_exp_before_2024[rb_exp_before_2024.duplicated(subset=['year', 'player_name', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [year, player_name, team, age, len_with_team]
Index: []

In [42]:
duplicates = rb_exp_2024[rb_exp_2024.duplicated(subset=['year', 'player_name', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [year, player_name, team, age, len_with_team]
Index: []

In [43]:
rb_inj_before_2024 = pd.read_pickle('pickles/rb_inj_before_2024.pickle')
rb_inj_2024 = pd.read_pickle('pickles/rb_inj_2024.pickle')
duplicates = rb_inj_before_2024[rb_inj_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
duplicates

     year  week  team          player_name  Injury  Wed  Thu  Fri  Game Status
121  2022     7     7  Christian McCaffrey      66    3    4    4            1
132  2022     7     7  Christian McCaffrey      69    4    4    2            1

In [44]:
rb_inj_before_2024 = rb_inj_before_2024.drop(index=132)

In [45]:
duplicates = rb_inj_before_2024[rb_inj_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [year, week, team, player_name, Injury, Wed, Thu, Fri, Game Status]
Index: []

In [46]:
duplicates = rb_inj_2024[rb_inj_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [year, week, team, player_name, Injury, Wed, Thu, Fri, Game Status]
Index: []

In [47]:
rb_sal = pd.read_pickle('pickles/rb_salaries.pickle')
duplicates = rb_sal[rb_sal.duplicated(subset=['player_name', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [player_name, team, Total Value, APY, Total Guaranteed, Avg. Guarantee/Year, % Guaranteed]
Index: []

### Using team val from og rb dfs, drop others

In [48]:
rb_exp_before_2024 = rb_exp_before_2024.drop(columns=['team'])
rb_exp_2024 = rb_exp_2024.drop(columns=['team'])
rb_inj_before_2024 = rb_inj_before_2024.drop(columns=['team'])
rb_inj_2024 = rb_inj_2024.drop(columns=['team'])
rb_sal = rb_sal.drop(columns=['team'])

### Merge rb and exp

In [49]:
rb_before_2024 = rb_before_2024.merge(rb_exp_before_2024, on=['year', 'player_name'], how='left')
rb_2024 = rb_2024.merge(rb_exp_2024, on=['year', 'player_name'], how='left')

In [50]:
rb_before_2024[rb_before_2024.isna().any(axis=1)]

,week,player_name,opponent_team,team,year,points,depth_team,prev_completions,prev_attempts,prev_passing_yards,...,cum_receiving_first_downs,cum_receiving_epa,cum_receiving_2pt_conversions,cum_racr,cum_target_share,cum_air_yards_share,cum_wopr,cum_points,age,len_with_team
238,1,Chris Rodriguez Jr.,13,20,2023,0.700000,3,0,0,0.0,...,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
239,6,Chris Rodriguez Jr.,16,20,2023,2.300000,3,0,0,0.0,...,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.700000,NaN,NaN
240,7,Chris Rodriguez Jr.,29,20,2023,3.100000,3,0,0,0.0,...,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,3.000000,NaN,NaN
241,11,Chris Rodriguez Jr.,29,20,2023,3.800000,2,0,0,0.0,...,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,6.100000,NaN,NaN
242,12,Chris Rodriguez Jr.,0,20,2023,2.100000,2,0,0,0.0,...,1,0.386434,0,-1.000000,0.023810,-0.019305,0.022201,9.900000,NaN,NaN
243,13,Chris Rodriguez Jr.,5,20,2023,2.900000,3,0,0,0.0,...,1,0.386434,0,-1.000000,0.023810,-0.019305,0.022201,12.000000,NaN,NaN
244,15,Chris Rodriguez Jr.,7,20,2023,3.500000,3,0,0,0.0,...,1,0.386434,0,-1.000000,0.023810,-0.019305,0.022201,14.900000,NaN,NaN
245,16,Chris Rodriguez Jr.,31,20,2023,19.500000,3,0,0,0.0,...,1,0.386434,0,-1.000000,0.023810,-0.019305,0.022201,18.400000,NaN,NaN
619,4,JaMycal Hasty,16,12,2023,0.000000,4,0,0,0.0,...,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
933,1,Kenneth Walker III,7,22,2023,10.700000,4,0,0,0.0,...,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
934,2,Kenneth Walker III,4,22,2023,18.400000,4,0,0,0.0,...,1,-3.196621,0,-0.115385,0.208333,-0.213115,0.163320,10.700000,NaN,NaN
935,3,Kenneth Walker III,26,22,2023,30.600000,4,0,0,0.0,...,2,-2.363341,0,-1.686813,0.262387,-0.244505,0.222428,29.099999,NaN,NaN
936,4,Kenneth Walker III,29,22,2023,13.900000,4,0,0,0.0,...,4,1.318569,0,1.783775,0.348102,-0.188399,0.390273,59.700000,NaN,NaN
937,6,Kenneth Walker III,14,22,2023,17.900000,4,0,0,0.0,...,4,1.318569,0,1.783775,0.348102,-0.188399,0.390273,73.599999,NaN,NaN
938,7,Kenneth Walker III,13,22,2023,13.100000,3,0,0,0.0,...,5,2.898506,0,1.783775,0.429183,-0.188399,0.511895,91.499999,NaN,NaN
939,8,Kenneth Walker III,17,22,2023,8.000000,4,0,0,0.0,...,5,2.379453,0,1.183775,0.554183,-0.232067,0.668827,104.599999,NaN,NaN
940,9,Kenneth Walker III,6,22,2023,2.700000,4,0,0,0.0,...,5,1.526408,0,1.469489,0.609738,-0.181888,0.787286,112.599999,NaN,NaN
941,10,Kenneth Walker III,20,22,2023,19.700001,4,0,0,0.0,...,5,0.270065,0,2.469489,0.689738,-0.176786,0.910857,115.299999,NaN,NaN
942,11,Kenneth Walker III,7,22,2023,2.600000,4,0,0,0.0,...,6,4.441240,0,-10.330511,0.737357,-0.196166,0.968720,135.000000,NaN,NaN
943,14,Kenneth Walker III,1,22,2023,9.400000,3,0,0,0.0,...,6,3.281606,0,-9.930511,0.763673,-0.211646,0.997358,137.600000,NaN,NaN
944,15,Kenneth Walker III,3,22,2023,20.200001,3,0,0,0.0,...,7,2.958607,0,-12.287654,0.924963,-0.271220,1.197591,147.000000,NaN,NaN
945,16,Kenneth Walker III,25,22,2023,6.600000,4,0,0,0.0,...,8,4.054977,0,-13.912654,1.018713,-0.338731,1.290959,167.200001,NaN,NaN
946,17,Kenneth Walker III,28,22,2023,16.500000,3,0,0,0.0,...,8,3.242600,0,-14.094472,1.074269,-0.386145,1.341102,173.800000,NaN,NaN
947,18,Kenneth Walker III,13,22,2023,9.100000,3,0,0,0.0,...,9,4.014510,0,-16.294472,1.165178,-0.430589,1.446355,190.300000,NaN,NaN
1428,2,Velus Jones Jr.,24,19,2023,-0.300000,4,0,0,0.0,...,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
1429,4,Velus Jones Jr.,23,19,2023,1.000000,4,0,0,0.0,...,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,-0.300000,NaN,NaN
1430,6,Velus Jones Jr.,9,19,2023,3.000000,3,0,0,0.0,...,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.700000,NaN,NaN
1431,7,Velus Jones Jr.,27,19,2023,1.000000,4,0,0,0.0,...,0,0.109273,0,1.000000,0.041667,0.035211,0.087148,3.700000,NaN,NaN
1432,8,Velus Jones Jr.,21,19,2023,1.400000,4,0,0,0.0,...,0,-0.753451,0,1.000000,0.076149,-0.096864,0.046419,4.700000,NaN,NaN
1433,9,Velus Jones Jr.,11,19,2023,0.000000,4,0,0,0.0,...,0,-1.530556,0,1.090909,0.130203,0.076364,0.248760,6.100000,NaN,NaN
1434,14,Velus Jones Jr.,4,19,2023,2.100000,4,0,0,0.0,...,0,-2.132852,0,1.090909,0.168665,0.058820,0.294172,6.100000,NaN,NaN
1435,15,Velus Jones Jr.,17,19,2023,2.300000,4,0,0,0.0,...,1,-1.008594,0,4.757576,0.201998,0.071807,0.353263,8.200000,NaN,NaN
1436,16,Velus Jones Jr.,13,19,2023,0.400000,4,0,0,0.0,...,1,-1.008594,0,4.757576,0.201998,0.071807,0.353263,10.500000,NaN,NaN
1437,17,Velus Jones Jr.,16,19,2023,0.200000,4,0,0,0.0,...,1,-1.528325,0,4.757576,0.245477,0.244884,0.539634,10.900000,NaN,NaN

In [51]:
rb_before_2024.loc[rb_before_2024['player_name'] == 'Kenneth Walker III', ['age', 'len_with_team']] = [23, 2]
rb_before_2024.loc[rb_before_2024['player_name'] == 'Chris Rodriguez Jr.', ['age', 'len_with_team']] = [23, 1]
rb_before_2024 = rb_before_2024.dropna()

In [52]:
rb_before_2024[rb_before_2024.isna().any(axis=1)]

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team]
Index: []

[0 rows x 88 columns]

In [53]:
rb_2024[rb_2024.isna().any(axis=1)]

,week,player_name,opponent_team,team,year,points,depth_team,prev_completions,prev_attempts,prev_passing_yards,...,cum_receiving_first_downs,cum_receiving_epa,cum_receiving_2pt_conversions,cum_racr,cum_target_share,cum_air_yards_share,cum_wopr,cum_points,age,len_with_team
94,1,Audric Estime,22,23,2024,1.4,3,0,0,0.0,...,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
95,6,Audric Estime,21,23,2024,1.3,3,0,0,0.0,...,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,1.400000,NaN,NaN
96,7,Audric Estime,11,23,2024,0.9,3,0,0,0.0,...,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,2.700000,NaN,NaN
97,8,Audric Estime,26,23,2024,0.4,3,0,0,0.0,...,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,3.600000,NaN,NaN
98,9,Audric Estime,6,23,2024,3.5,3,0,0,0.0,...,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,4.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1438,16,Tyrone Tracy,16,29,2024,16.9,2,0,0,0.0,...,10,-8.731932,0,-39.454579,1.252327,0.108481,1.954428,147.499999,NaN,NaN
1439,17,Tyrone Tracy,18,29,2024,9.3,2,0,0,0.0,...,13,-2.780550,0,-43.037912,1.360436,0.053435,2.078058,164.399999,NaN,NaN
1440,18,Tyrone Tracy,3,29,2024,8.6,2,0,0,0.0,...,13,-4.090828,0,-41.287912,1.496799,0.097151,2.313204,173.699999,NaN,NaN
1441,1,Velus Jones,25,19,2024,2.9,1,0,0,0.0,...,0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
1442,17,Velus Jones,24,26,2024,0.0,4,0,0,0.0,...,0,0.564906,0,-1.600000,0.034483,-0.023364,0.035369,2.900000,NaN,NaN

In [54]:
rb_2024[rb_2024.isna().any(axis=1)]['player_name'].unique()

array(['Audric Estime', 'Ben VanSumeren', 'Chris Rodriguez',
       'Christopher Brooks', 'Devon Achane', 'Jamycal Hasty',
       'Jeffery Wilson', 'Kenneth Walker', 'Tyrone Tracy', 'Velus Jones'],
      dtype=object)

In [55]:
rb_2024['age'].fillna(rb_2024['age'].median(), inplace=True)
rb_2024['len_with_team'].fillna(rb_2024['len_with_team'].median(), inplace=True)

In [56]:
rb_2024[rb_2024.isna().any(axis=1)]

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team]
Index: []

[0 rows x 88 columns]

In [57]:
print(rb_before_2024.isna().any().any())
print(rb_2024.isna().any().any())

False
False

In [58]:
duplicates = rb_before_2024[rb_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
print(duplicates)
duplicates = rb_2024[rb_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team]
Index: []

[0 rows x 88 columns]

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team]
Index: []

[0 rows x 88 columns]

### Merge rb with injuries

In [59]:
rb_before_2024 = rb_before_2024.merge(rb_inj_before_2024, on=['year', 'week', 'player_name'], how='left')
rb_2024 = rb_2024.merge(rb_inj_2024, on=['year', 'week', 'player_name'], how='left')

In [60]:
rb_before_2024[rb_before_2024.isna().any(axis=1)]

,week,player_name,opponent_team,team,year,points,depth_team,prev_completions,prev_attempts,prev_passing_yards,...,cum_air_yards_share,cum_wopr,cum_points,age,len_with_team,Injury,Wed,Thu,Fri,Game Status
2,3,AJ Dillon,11,10,2023,3.3,4,0,0,0.0,...,-0.003719,0.224064,12.900000,25.0,1.0,NaN,NaN,NaN,NaN,NaN
3,4,AJ Dillon,4,10,2023,1.1,2,0,0,0.0,...,-0.003719,0.224064,16.200000,25.0,1.0,NaN,NaN,NaN,NaN,NaN
4,5,AJ Dillon,27,10,2023,13.6,1,0,0,0.0,...,0.014299,0.280794,17.300000,25.0,1.0,NaN,NaN,NaN,NaN,NaN
5,7,AJ Dillon,23,10,2023,11.5,4,0,0,0.0,...,-0.006277,0.318115,30.900000,25.0,1.0,NaN,NaN,NaN,NaN,NaN
6,8,AJ Dillon,9,10,2023,10.2,2,0,0,0.0,...,0.002773,0.418200,42.400000,25.0,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1471,14,Zamir White,9,27,2023,0.8,2,0,0,0.0,...,0.044096,0.285334,12.400000,23.0,2.0,NaN,NaN,NaN,NaN,NaN
1472,15,Zamir White,21,27,2023,17.5,2,0,0,0.0,...,0.044096,0.285334,13.200000,23.0,2.0,NaN,NaN,NaN,NaN,NaN
1473,16,Zamir White,8,27,2023,14.5,2,0,0,0.0,...,0.069096,0.479304,30.700000,23.0,2.0,NaN,NaN,NaN,NaN,NaN
1474,17,Zamir White,18,27,2023,15.6,2,0,0,0.0,...,0.016808,0.521650,45.200000,23.0,2.0,NaN,NaN,NaN,NaN,NaN
1475,18,Zamir White,23,27,2023,13.1,1,0,0,0.0,...,-0.000391,0.705263,60.800001,23.0,2.0,NaN,NaN,NaN,NaN,NaN

In [61]:
rb_before_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']] = rb_before_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']].fillna(0)
rb_before_2024[rb_before_2024.isna().any(axis=1)]

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status]
Index: []

[0 rows x 93 columns]

In [62]:
rb_2024[rb_2024.isna().any(axis=1)]

,week,player_name,opponent_team,team,year,points,depth_team,prev_completions,prev_attempts,prev_passing_yards,...,cum_air_yards_share,cum_wopr,cum_points,age,len_with_team,Injury,Wed,Thu,Fri,Game Status
1,2,Aaron Jones,1,9,2024,9.8,1,0,0,0.0,...,0.033708,0.154030,18.900000,29.0,1.0,NaN,NaN,NaN,NaN,NaN
3,4,Aaron Jones,10,9,2024,17.9,1,0,0,0.0,...,-0.082193,0.807899,54.499999,29.0,1.0,NaN,NaN,NaN,NaN,NaN
4,5,Aaron Jones,31,9,2024,6.3,1,0,0,0.0,...,-0.009201,1.136772,72.399999,29.0,1.0,NaN,NaN,NaN,NaN,NaN
7,9,Aaron Jones,18,9,2024,12.2,1,0,0,0.0,...,0.145041,1.601824,110.799999,29.0,1.0,NaN,NaN,NaN,NaN,NaN
8,10,Aaron Jones,12,9,2024,12.1,1,0,0,0.0,...,0.100507,1.752469,122.999999,29.0,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,2,Zamir White,6,27,2024,6.8,1,0,0,0.0,...,-0.020548,0.079366,4.600000,24.0,3.0,NaN,NaN,NaN,NaN,NaN
1476,3,Zamir White,26,27,2024,3.4,1,0,0,0.0,...,-0.070322,0.211191,11.400000,24.0,3.0,NaN,NaN,NaN,NaN,NaN
1477,4,Zamir White,17,27,2024,3.0,1,0,0,0.0,...,-0.070322,0.211191,14.800000,24.0,3.0,NaN,NaN,NaN,NaN,NaN
1479,8,Zamir White,8,27,2024,-0.1,1,0,0,0.0,...,-0.121436,0.280768,21.500000,24.0,3.0,NaN,NaN,NaN,NaN,NaN
1481,11,Zamir White,5,27,2024,0.9,1,0,0,0.0,...,-0.121436,0.280768,28.400000,24.0,3.0,NaN,NaN,NaN,NaN,NaN

In [63]:
rb_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']] = rb_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']].fillna(0)
rb_2024[rb_2024.isna().any(axis=1)]

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status]
Index: []

[0 rows x 93 columns]

In [64]:
duplicates = rb_before_2024[rb_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
print(duplicates)
duplicates = rb_2024[rb_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False)]
duplicates

     week    player_name  opponent_team  team  year     points depth_team  \
596     3  Isiah Pacheco             19     8  2023  15.800000          1
597     3  Isiah Pacheco             19     8  2023  15.800000          1
598     4  Isiah Pacheco             31     8  2023  24.799999          1
599     4  Isiah Pacheco             31     8  2023  24.799999          1

     prev_completions  prev_attempts  prev_passing_yards  ...  \
596                 0              0                 0.0  ...
597                 0              0                 0.0  ...
598                 0              0                 0.0  ...
599                 0              0                 0.0  ...

     cum_air_yards_share  cum_wopr  cum_points   age  len_with_team  Injury  \
596            -0.054562  0.198969        17.4  24.0            2.0     4.0
597            -0.054562  0.198969        17.4  24.0            2.0    69.0
598            -0.086691  0.298100        33.2  24.0            2.0    11.0
599            -0.086691  0.298100        33.2  24.0            2.0    69.0

     Wed  Thu  Fri  Game Status
596  3.0  2.0  2.0          2.0
597  3.0  3.0  2.0          2.0
598  1.0  1.0  1.0          1.0
599  1.0  1.0  1.0          1.0

[4 rows x 93 columns]

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status]
Index: []

[0 rows x 93 columns]

In [65]:
rb_before_2024.drop(index=[597, 599], inplace=True)

In [66]:
duplicates = rb_before_2024[rb_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
print(duplicates)
duplicates = rb_2024[rb_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status]
Index: []

[0 rows x 93 columns]

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status]
Index: []

[0 rows x 93 columns]

### Merge rb with sal

In [67]:
rb_before_2024 = rb_before_2024.merge(rb_sal, on=['player_name'], how='left')
rb_2024 = rb_2024.merge(rb_sal, on=['player_name'], how='left')

In [68]:
duplicates = rb_before_2024[rb_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
print(duplicates)
duplicates = rb_2024[rb_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status, Total Value, APY, Total Guaranteed, Avg. Guarantee/Year, % Guaranteed]
Index: []

[0 rows x 98 columns]

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status, Total Value, APY, Total Guaranteed, Avg. Guarantee/Year, % Guaranteed]
Index: []

[0 rows x 98 columns]

In [69]:
print(rb_before_2024.isna().any().any())
print(rb_2024.isna().any().any())

True
True

In [70]:
cols = ['Total Value', 'APY', 'Total Guaranteed', 'Avg. Guarantee/Year', '% Guaranteed']
for df in [rb_before_2024, rb_2024]:
    for col in cols:
        df[col].fillna(df[col].mean(), inplace=True)

In [71]:
print(rb_before_2024.isna().any().any())
print(rb_2024.isna().any().any())

False
False

### Merge with previous data

In [72]:
rb_before_2024 = rb_before_2024.merge(f_before_2024, on=['year', 'week', 'team'], how='left')
rb_2024 = rb_2024.merge(f_2024, on=['year', 'week', 'team'], how='left')

In [73]:
print(rb_before_2024.isna().any().any())
print(rb_2024.isna().any().any())

False
False

In [74]:
duplicates = rb_before_2024[rb_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status, Total Value, APY, Total Guaranteed, Avg. Guarantee/Year, % Guaranteed, G-season, W-season, ...]
Index: []

[0 rows x 150 columns]

In [75]:
duplicates = rb_2024[rb_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points, age, len_with_team, Injury, Wed, Thu, Fri, Game Status, Total Value, APY, Total Guaranteed, Avg. Guarantee/Year, % Guaranteed, G-season, W-season, ...]
Index: []

[0 rows x 150 columns]

### Append to final_dfs

In [76]:
final_dfs.append([rb_before_2024, rb_2024])

In [77]:
len(final_dfs)

2

In [78]:
subset = rb_2024[(rb_2024['player_name'].isin(['Christian McCaffrey', 'Isaac Guerendo'])) & (rb_2024['week'] == 1)]

for index, row in subset.iterrows():
    print(" | ".join([f"{col}: {val}" for col, val in zip(subset.columns, row.values)]))
    print("-" * 50)

week: 1 | player_name: Christian McCaffrey | opponent_team: 31 | team: 1 | year: 2024 | points: 0.0 | depth_team: 1 | prev_completions: 1 | prev_attempts: 2 | prev_passing_yards: 34.0 | prev_passing_tds: 1 | prev_interceptions: 0.0 | prev_sacks: 0.0 | prev_sack_yards: 0.0 | prev_sack_fumbles: 0 | prev_sack_fumbles_lost: 0 | prev_passing_air_yards: 70.0 | prev_passing_yards_after_catch: 3.0 | prev_passing_first_downs: 1.0 | prev_passing_epa: 3.2338061332702637 | prev_passing_2pt_conversions: 0 | prev_pacr: 1.0967742204666138 | prev_dakota: 0.0 | prev_carries: 714 | prev_rushing_yards: 3546.0 | prev_rushing_tds: 29 | prev_rushing_fumbles: 5.0 | prev_rushing_fumbles_lost: 3.0 | prev_rushing_first_downs: 191.0 | prev_rushing_epa: 22.668062210083008 | prev_rushing_2pt_conversions: 0 | prev_receptions: 220 | prev_targets: 271 | prev_receiving_yards: 1861.0 | prev_receiving_tds: 15 | prev_receiving_fumbles: 1.0 | prev_receiving_fumbles_lost: 0.0 | prev_receiving_air_yards: 434.0 | prev_receiving_yards_after_catch: 1617.0 | prev_receiving_first_downs: 97.0 | prev_receiving_epa: 49.574623107910156 | prev_receiving_2pt_conversions: 0 | prev_racr: -9.143157005310059 | prev_target_share: 9.350225448608398 | prev_air_yards_share: 1.2979696989059448 | prev_wopr: 14.933917999267578 | cum_completions: 0 | cum_attempts: 0 | cum_passing_yards: 0 | cum_passing_tds: 0 | cum_interceptions: 0 | cum_sacks: 0 | cum_sack_yards: 0 | cum_sack_fumbles: 0 | cum_sack_fumbles_lost: 0 | cum_passing_air_yards: 0 | cum_passing_yards_after_catch: 0 | cum_passing_first_downs: 0 | cum_passing_epa: 0.0 | cum_passing_2pt_conversions: 0 | cum_pacr: 0 | cum_dakota: 0 | cum_carries: 0 | cum_rushing_yards: 0 | cum_rushing_tds: 0 | cum_rushing_fumbles: 0 | cum_rushing_fumbles_lost: 0 | cum_rushing_first_downs: 0 | cum_rushing_epa: 0.0 | cum_rushing_2pt_conversions: 0 | cum_receptions: 0 | cum_targets: 0 | cum_receiving_yards: 0 | cum_receiving_tds: 0 | cum_receiving_fumbles: 0 | cum_receiving_fumbles_lost: 0 | cum_receiving_air_yards: 0 | cum_receiving_yards_after_catch: 0 | cum_receiving_first_downs: 0 | cum_receiving_epa: 0.0 | cum_receiving_2pt_conversions: 0 | cum_racr: 0.0 | cum_target_share: 0.0 | cum_air_yards_share: 0.0 | cum_wopr: 0.0 | cum_points: 0.0 | age: 28.0 | len_with_team: 3.0 | Injury: 52 | Wed: 2 | Thu: 2 | Fri: 2 | Game Status: 2 | Total Value: 38000000.0 | APY: 19000000.0 | Total Guaranteed: 24000000.0 | Avg. Guarantee/Year: 12000000.0 | % Guaranteed: 0.632 | G-season: 17 | W-season: 12 | L-season: 5 | T-season: 0 | G-w/team: 132 | W-w/team: 70 | L-w/team: 62 | T-w/team: 0 | G-career: 132 | W-career: 70 | L-career: 62 | T-career: 0 | G plyf-playoffs: 3 | W plyf-playoffs: 2 | L plyf-playoffs: 1 | G plyf-w/team: 12 | W plyf-w/team: 8 | L plyf-w/team: 4 | G plyf-career: 12 | W plyf-career: 8 | L plyf-career: 4 | Remark: 5 | w/same_team: 1.0 | Gms-fds: 17 | Rush-fds: 147 | Pass-fds: 207 | Pen-fds: 29 | Pct-tde: 47.5 | Pct-fde: 53.8 | gameday: 3 | weekday: 1 | gametime: 10 | away_team: 31 | home_team: 1 | away_moneyline: 150.0 | home_moneyline: -180.0 | spread_line: 3.5 | away_spread_odds: -115.0 | home_spread_odds: -105.0 | total_line: 43.0 | under_odds: -108.0 | over_odds: -112.0 | div_game: 0 | roof: 2 | surface: 3 | temp: 76.0 | wind: 10.0 | referee: 6 | stadium: 14 | bye_week: 9 | oline_rank: 24 | dline_rank: 5
--------------------------------------------------
week: 1 | player_name: Isaac Guerendo | opponent_team: 31 | team: 1 | year: 2024 | points: 0.0 | depth_team: 3 | prev_completions: 0 | prev_attempts: 0 | prev_passing_yards: 0.0 | prev_passing_tds: 0 | prev_interceptions: 0.0 | prev_sacks: 0.0 | prev_sack_yards: 0.0 | prev_sack_fumbles: 0 | prev_sack_fumbles_lost: 0 | prev_passing_air_yards: 0.0 | prev_passing_yards_after_catch: 0.0 | prev_passing_first_downs: 0.0 | prev_passing_epa: 0.0 | prev_passing_2pt_conversions: 0 | prev_pacr: 0.0 | prev_dakota: 0.0 | prev_carries: 0 | prev_rushing_yards: 0.0 | prev_rushing_tds: 0 | prev_rushing_fumbles: 0.0 | prev_rushing_fumbles_lost: 0.0 | prev_rushing_first_downs: 0.0 | prev_rushing_epa: 0.0 | prev_rushing_2pt_conversions: 0 | prev_receptions: 0 | prev_targets: 0 | prev_receiving_yards: 0.0 | prev_receiving_tds: 0 | prev_receiving_fumbles: 0.0 | prev_receiving_fumbles_lost: 0.0 | prev_receiving_air_yards: 0.0 | prev_receiving_yards_after_catch: 0.0 | prev_receiving_first_downs: 0.0 | prev_receiving_epa: 0.0 | prev_receiving_2pt_conversions: 0 | prev_racr: 0.0 | prev_target_share: 0.0 | prev_air_yards_share: 0.0 | prev_wopr: 0.0 | cum_completions: 0 | cum_attempts: 0 | cum_passing_yards: 0 | cum_passing_tds: 0 | cum_interceptions: 0 | cum_sacks: 0 | cum_sack_yards: 0 | cum_sack_fumbles: 0 | cum_sack_fumbles_lost: 0 | cum_passing_air_yards: 0 | cum_passing_yards_after_catch: 0 | cum_passing_first_downs: 0 | cum_passing_epa: 0.0 | cum_passing_2pt_conversions: 0 | cum_pacr: 0 | cum_dakota: 0 | cum_carries: 0 | cum_rushing_yards: 0 | cum_rushing_tds: 0 | cum_rushing_fumbles: 0 | cum_rushing_fumbles_lost: 0 | cum_rushing_first_downs: 0 | cum_rushing_epa: 0.0 | cum_rushing_2pt_conversions: 0 | cum_receptions: 0 | cum_targets: 0 | cum_receiving_yards: 0 | cum_receiving_tds: 0 | cum_receiving_fumbles: 0 | cum_receiving_fumbles_lost: 0 | cum_receiving_air_yards: 0 | cum_receiving_yards_after_catch: 0 | cum_receiving_first_downs: 0 | cum_receiving_epa: 0.0 | cum_receiving_2pt_conversions: 0 | cum_racr: 0.0 | cum_target_share: 0.0 | cum_air_yards_share: 0.0 | cum_wopr: 0.0 | cum_points: 0.0 | age: 24.0 | len_with_team: 1.0 | Injury: 16 | Wed: 2 | Thu: 2 | Fri: 1 | Game Status: 1 | Total Value: 4724528.0 | APY: 1181132.0 | Total Guaranteed: 704525.0 | Avg. Guarantee/Year: 176131.0 | % Guaranteed: 0.149 | G-season: 17 | W-season: 12 | L-season: 5 | T-season: 0 | G-w/team: 132 | W-w/team: 70 | L-w/team: 62 | T-w/team: 0 | G-career: 132 | W-career: 70 | L-career: 62 | T-career: 0 | G plyf-playoffs: 3 | W plyf-playoffs: 2 | L plyf-playoffs: 1 | G plyf-w/team: 12 | W plyf-w/team: 8 | L plyf-w/team: 4 | G plyf-career: 12 | W plyf-career: 8 | L plyf-career: 4 | Remark: 5 | w/same_team: 1.0 | Gms-fds: 17 | Rush-fds: 147 | Pass-fds: 207 | Pen-fds: 29 | Pct-tde: 47.5 | Pct-fde: 53.8 | gameday: 3 | weekday: 1 | gametime: 10 | away_team: 31 | home_team: 1 | away_moneyline: 150.0 | home_moneyline: -180.0 | spread_line: 3.5 | away_spread_odds: -115.0 | home_spread_odds: -105.0 | total_line: 43.0 | under_odds: -108.0 | over_odds: -112.0 | div_game: 0 | roof: 2 | surface: 3 | temp: 76.0 | wind: 10.0 | referee: 6 | stadium: 14 | bye_week: 9 | oline_rank: 24 | dline_rank: 5
--------------------------------------------------

# 3. Wide Receivers

In [79]:
wr_before_2024 = pd.read_pickle('pickles/wr_before_2024.pickle')
wr_2024 = pd.read_pickle('pickles/wr_2024.pickle')
duplicates = wr_before_2024[wr_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points]
Index: []

[0 rows x 86 columns]

In [80]:
duplicates = wr_2024[wr_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [week, player_name, opponent_team, team, year, points, depth_team, prev_completions, prev_attempts, prev_passing_yards, prev_passing_tds, prev_interceptions, prev_sacks, prev_sack_yards, prev_sack_fumbles, prev_sack_fumbles_lost, prev_passing_air_yards, prev_passing_yards_after_catch, prev_passing_first_downs, prev_passing_epa, prev_passing_2pt_conversions, prev_pacr, prev_dakota, prev_carries, prev_rushing_yards, prev_rushing_tds, prev_rushing_fumbles, prev_rushing_fumbles_lost, prev_rushing_first_downs, prev_rushing_epa, prev_rushing_2pt_conversions, prev_receptions, prev_targets, prev_receiving_yards, prev_receiving_tds, prev_receiving_fumbles, prev_receiving_fumbles_lost, prev_receiving_air_yards, prev_receiving_yards_after_catch, prev_receiving_first_downs, prev_receiving_epa, prev_receiving_2pt_conversions, prev_racr, prev_target_share, prev_air_yards_share, prev_wopr, cum_completions, cum_attempts, cum_passing_yards, cum_passing_tds, cum_interceptions, cum_sacks, cum_sack_yards, cum_sack_fumbles, cum_sack_fumbles_lost, cum_passing_air_yards, cum_passing_yards_after_catch, cum_passing_first_downs, cum_passing_epa, cum_passing_2pt_conversions, cum_pacr, cum_dakota, cum_carries, cum_rushing_yards, cum_rushing_tds, cum_rushing_fumbles, cum_rushing_fumbles_lost, cum_rushing_first_downs, cum_rushing_epa, cum_rushing_2pt_conversions, cum_receptions, cum_targets, cum_receiving_yards, cum_receiving_tds, cum_receiving_fumbles, cum_receiving_fumbles_lost, cum_receiving_air_yards, cum_receiving_yards_after_catch, cum_receiving_first_downs, cum_receiving_epa, cum_receiving_2pt_conversions, cum_racr, cum_target_share, cum_air_yards_share, cum_wopr, cum_points]
Index: []

[0 rows x 86 columns]

In [81]:
wr_exp_before_2024 = pd.read_pickle('pickles/wr_exp_before_2024.pickle')
wr_exp_2024 = pd.read_pickle('pickles/wr_exp_2024.pickle')
duplicates = wr_exp_before_2024[wr_exp_before_2024.duplicated(subset=['year', 'player_name', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [year, player_name, team, age, len_with_team]
Index: []

In [82]:
duplicates = wr_exp_2024[wr_exp_2024.duplicated(subset=['year', 'player_name', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [year, player_name, team, age, len_with_team]
Index: []

In [83]:
wr_inj_before_2024 = pd.read_pickle('pickles/wr_inj_before_2024.pickle')
wr_inj_2024 = pd.read_pickle('pickles/wr_inj_2024.pickle')
duplicates = wr_inj_before_2024[wr_inj_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [year, week, team, player_name, Injury, Wed, Thu, Fri, Game Status]
Index: []

In [84]:
duplicates = wr_inj_2024[wr_inj_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [year, week, team, player_name, Injury, Wed, Thu, Fri, Game Status]
Index: []

In [85]:
wr_sal = pd.read_pickle('pickles/wr_salaries.pickle')
duplicates = wr_sal[wr_sal.duplicated(subset=['player_name', 'team'], keep=False)]
duplicates

Empty DataFrame
Columns: [player_name, team, Total Value, APY, Total Guaranteed, Avg. Guarantee/Year, % Guaranteed]
Index: []

### Using team val from og wr dfs, drop others

In [86]:
wr_exp_before_2024 = wr_exp_before_2024.drop(columns=['team'])
wr_exp_2024 = wr_exp_2024.drop(columns=['team'])
wr_inj_before_2024 = wr_inj_before_2024.drop(columns=['team'])
wr_inj_2024 = wr_inj_2024.drop(columns=['team'])
wr_sal = wr_sal.drop(columns=['team'])

### Merge wr and exp

In [87]:
wr_before_2024 = wr_before_2024.merge(wr_exp_before_2024, on=['year', 'player_name'], how='left')
wr_2024 = wr_2024.merge(wr_exp_2024, on=['year', 'player_name'], how='left')

In [88]:
print(wr_before_2024.isna().any().any())
print(wr_2024.isna().any().any())

True
True

In [89]:
wr_before_2024['age'].fillna(wr_before_2024['age'].median(), inplace=True)
wr_before_2024['len_with_team'].fillna(wr_before_2024['len_with_team'].median(), inplace=True)
wr_2024['age'].fillna(wr_2024['age'].median(), inplace=True)
wr_2024['len_with_team'].fillna(wr_2024['len_with_team'].median(), inplace=True)

In [90]:
print(wr_before_2024.isna().any().any())
print(wr_2024.isna().any().any())

False
False

In [91]:
print(wr_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False).any())
print(wr_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False).any())

False
False

### Merge wr with injuries

In [92]:
wr_before_2024 = wr_before_2024.merge(wr_inj_before_2024, on=['year', 'week', 'player_name'], how='left')
wr_2024 = wr_2024.merge(wr_inj_2024, on=['year', 'week', 'player_name'], how='left')

In [93]:
print(wr_before_2024.isna().any().any())
print(wr_2024.isna().any().any())

True
True

In [94]:
wr_before_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']] = wr_before_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']].fillna(0)
wr_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']] = wr_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']].fillna(0)

In [95]:
print(wr_before_2024.isna().any().any())
print(wr_2024.isna().any().any())

False
False

In [96]:
duplicates = wr_before_2024[wr_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
print(duplicates)
duplicates = wr_2024[wr_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False)]
duplicates

      week       player_name  opponent_team  team  year  points depth_team  \
96       1      Amari Cooper             14    17  2023     6.7          1
97       1      Amari Cooper             14    17  2023     6.7          1
1124     1     Jaylen Waddle             21     5  2023    11.8          3
1125     1     Jaylen Waddle             21     5  2023    11.8          3
1331     1    Kadarius Toney              4     8  2023     1.0          2
1332     1    Kadarius Toney              4     8  2023     1.0          2
1333     2    Kadarius Toney             12     8  2023     8.8          2
1334     2    Kadarius Toney             12     8  2023     8.8          2
1335     3    Kadarius Toney             19     8  2023     0.9          1
1336     3    Kadarius Toney             19     8  2023     0.9          1
1522     1  Marquise Goodwin             14    17  2023     0.0          2
1523     1  Marquise Goodwin             14    17  2023     0.0          2
1892     2      Robert Woods             18    15  2023    13.4          1
1893     2      Robert Woods             18    15  2023    13.4          1
1907     1       Romeo Doubs             19    10  2023    18.6          1
1908     1       Romeo Doubs             19    10  2023    18.6          1

      prev_completions  prev_attempts  prev_passing_yards  ...  \
96                   0              1                 0.0  ...
97                   0              1                 0.0  ...
1124                 0              0                 0.0  ...
1125                 0              0                 0.0  ...
1331                 1              3                19.0  ...
1332                 1              3                19.0  ...
1333                 1              3                19.0  ...
1334                 1              3                19.0  ...
1335                 1              3                19.0  ...
1336                 1              3                19.0  ...
1522                 0              0                 0.0  ...
1523                 0              0                 0.0  ...
1892                 0              0                 0.0  ...
1893                 0              0                 0.0  ...
1907                 0              0                 0.0  ...
1908                 0              0                 0.0  ...

      cum_air_yards_share  cum_wopr  cum_points   age  len_with_team  Injury  \
96               0.000000  0.000000         0.0  29.0            2.0    66.0
97               0.000000  0.000000         0.0  29.0            2.0    66.0
1124             0.000000  0.000000         0.0  24.0            3.0    17.0
1125             0.000000  0.000000         0.0  24.0            3.0    10.0
1331             0.000000  0.000000         0.0  24.0            2.0     1.0
1332             0.000000  0.000000         0.0  24.0            2.0    69.0
1333             0.119534  0.286376         1.0  24.0            2.0     1.0
1334             0.119534  0.286376         1.0  24.0            2.0    69.0
1335             0.112313  0.468822         9.8  24.0            2.0     9.0
1336             0.112313  0.468822         9.8  24.0            2.0     3.0
1522             0.000000  0.000000         0.0  32.0            1.0    62.0
1523             0.000000  0.000000         0.0  32.0            1.0     1.0
1892             0.288462  0.550760        11.7  31.0            1.0    66.0
1893             0.288462  0.550760        11.7  31.0            1.0     3.0
1907             0.000000  0.000000         0.0  23.0            2.0     4.0
1908             0.000000  0.000000         0.0  23.0            2.0    69.0

      Wed  Thu  Fri  Game Status
96    3.0  1.0  1.0          1.0
97    3.0  3.0  1.0          1.0
1124  2.0  1.0  1.0          1.0
1125  2.0  2.0  2.0          2.0
1331  2.0  2.0  1.0          1.0
1332  2.0  2.0  2.0          2.0
1333  1.0  1.0  1.0          1.0
1334  2.0  2.0  2.0          2.0
1335  3.0  3.0  2.0          2.0
1336  1.0  2.0  2.0          2.0
1522  2.0  2.0  2.0          1.0
1523  2.0  2.0  1.0          1.0
1892  2.0  1.0  1.0          1.0
1893  2.0  2.0  2.0          1.0
1907  3.0  2.0  2.0          2.0
1908  2.0  2.0  2.0          1.0

[16 rows x 93 columns]

,week,player_name,opponent_team,team,year,points,depth_team,prev_completions,prev_attempts,prev_passing_yards,...,cum_air_yards_share,cum_wopr,cum_points,age,len_with_team,Injury,Wed,Thu,Fri,Game Status
0,1,A.J. Brown,10,3,2024,22.9,1,0,2,0.0,...,0.0,0.000000,0.000000,27.0,3.0,66.0,2.0,1.0,1.0,1.0
1,1,A.J. Brown,10,3,2024,22.9,1,0,2,0.0,...,0.0,0.000000,0.000000,27.0,3.0,66.0,2.0,3.0,1.0,1.0
376,1,Curtis Samuel,13,2,2024,3.5,1,0,0,0.0,...,0.0,0.000000,0.000000,28.0,1.0,9.0,1.0,1.0,1.0,1.0
377,1,Curtis Samuel,13,2,2024,3.5,1,0,0,0.0,...,0.0,0.000000,0.000000,28.0,1.0,12.0,1.0,1.0,1.0,1.0
1158,1,Josh Palmer,27,21,2024,3.5,1,0,0,0.0,...,0.0,0.000000,0.000000,24.0,4.0,1.0,4.0,1.0,1.0,1.0
1159,1,Josh Palmer,27,21,2024,3.5,1,0,0,0.0,...,0.0,0.000000,0.000000,24.0,4.0,8.0,3.0,3.0,3.0,4.0
1570,1,Mike Evans,20,24,2024,23.1,1,0,0,0.0,...,0.0,0.000000,0.000000,31.0,11.0,66.0,4.0,4.0,2.0,1.0
1571,1,Mike Evans,20,24,2024,23.1,1,0,0,0.0,...,0.0,0.000000,0.000000,31.0,11.0,66.0,2.0,3.0,2.0,1.0
1634,2,Nico Collins,19,15,2024,27.5,1,0,0,0.0,...,0.5,0.737097,17.700001,25.0,4.0,62.0,4.0,2.0,1.0,1.0
1635,2,Nico Collins,19,15,2024,27.5,1,0,0,0.0,...,0.5,0.737097,17.700001,25.0,4.0,66.0,2.0,4.0,4.0,1.0
1829,1,Romeo Doubs,3,10,2024,9.0,1,0,0,0.0,...,0.0,0.000000,0.000000,24.0,3.0,69.0,2.0,2.0,1.0,1.0
1830,1,Romeo Doubs,3,10,2024,9.0,1,0,0,0.0,...,0.0,0.000000,0.000000,24.0,3.0,62.0,1.0,1.0,1.0,1.0

In [97]:
wr_before_2024.drop(index=[97, 1125, 1332, 1334, 1336, 1523, 1893, 1908], inplace=True)
wr_2024.drop(index=[1, 377, 1159, 1571, 1635, 1830], inplace=True)

In [98]:
print(wr_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False).any())
print(wr_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False).any())

False
False

### Merge wr with sal

In [99]:
wr_before_2024 = wr_before_2024.merge(wr_sal, on=['player_name'], how='left')
wr_2024 = wr_2024.merge(wr_sal, on=['player_name'], how='left')

In [100]:
print(wr_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False).any())
print(wr_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False).any())

False
False

In [101]:
print(wr_before_2024.isna().any().any())
print(wr_2024.isna().any().any())

True
True

In [102]:
cols = ['Total Value', 'APY', 'Total Guaranteed', 'Avg. Guarantee/Year', '% Guaranteed']
for df in [wr_before_2024, wr_2024]:
    for col in cols:
        df[col].fillna(df[col].mean(), inplace=True)

In [103]:
print(wr_before_2024.isna().any().any())
print(wr_2024.isna().any().any())

False
False

### Merge with previous data

In [104]:
wr_before_2024 = wr_before_2024.merge(f_before_2024, on=['year', 'week', 'team'], how='left')
wr_2024 = wr_2024.merge(f_2024, on=['year', 'week', 'team'], how='left')

In [105]:
print(wr_before_2024.isna().any().any())
print(wr_2024.isna().any().any())

False
False

In [106]:
print(wr_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False).any())
print(wr_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False).any())

False
False

### Append wr to final_dfs

In [107]:
final_dfs.append([wr_before_2024, wr_2024])

# 4. Tight Ends

In [108]:
te_before_2024 = pd.read_pickle('pickles/te_before_2024.pickle')
te_2024 = pd.read_pickle('pickles/te_2024.pickle')
print(te_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False).any())
print(te_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False).any())

False
False

In [109]:
print(te_before_2024.isna().any().any())
print(te_2024.isna().any().any())

False
False

In [110]:
te_exp_before_2024 = pd.read_pickle('pickles/te_exp_before_2024.pickle')
te_exp_2024 = pd.read_pickle('pickles/te_exp_2024.pickle')
print(te_exp_before_2024.duplicated(subset=['year', 'player_name', 'team'], keep=False).any())
print(te_exp_2024.duplicated(subset=['player_name', 'team'], keep=False).any())
print(te_exp_before_2024.isna().any().any())
print(te_exp_2024.isna().any().any())

False
False
False
False

In [111]:
te_inj_before_2024 = pd.read_pickle('pickles/te_inj_before_2024.pickle')
te_inj_2024 = pd.read_pickle('pickles/te_inj_2024.pickle')
print(te_inj_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False).any())
print(te_inj_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False).any())
print(te_inj_before_2024.isna().any().any())
print(te_inj_2024.isna().any().any())

False
False
False
False

In [112]:
te_sal = pd.read_pickle('pickles/te_salaries.pickle')
print(te_sal.duplicated(subset=['player_name', 'team'], keep=False).any())
print(te_sal.isna().any().any())

False
False

### Using team val from og te dfs, drop others

In [113]:
te_exp_before_2024 = te_exp_before_2024.drop(columns=['team'])
te_exp_2024 = te_exp_2024.drop(columns=['team'])
te_inj_before_2024 = te_inj_before_2024.drop(columns=['team'])
te_inj_2024 = te_inj_2024.drop(columns=['team'])
te_sal = te_sal.drop(columns=['team'])

### Merge te and exp

In [114]:
te_before_2024 = te_before_2024.merge(te_exp_before_2024, on=['year', 'player_name'], how='left')
te_2024 = te_2024.merge(te_exp_2024, on=['year', 'player_name'], how='left')

In [115]:
print(te_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False).any())
print(te_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False).any())

False
False

In [116]:
print(te_before_2024.isna().any().any())
print(te_2024.isna().any().any())

True
True

In [117]:
te_before_2024['age'].fillna(te_before_2024['age'].median(), inplace=True)
te_before_2024['len_with_team'].fillna(te_before_2024['len_with_team'].median(), inplace=True)
te_2024['age'].fillna(te_2024['age'].median(), inplace=True)
te_2024['len_with_team'].fillna(te_2024['len_with_team'].median(), inplace=True)

In [118]:
print(te_before_2024.isna().any().any())
print(te_2024.isna().any().any())

False
False

### Merge te with injuries

In [119]:
te_before_2024 = te_before_2024.merge(te_inj_before_2024, on=['year', 'week', 'player_name'], how='left')
te_2024 = te_2024.merge(te_inj_2024, on=['year', 'week', 'player_name'], how='left')

In [120]:
print(te_before_2024.isna().any().any())
print(te_2024.isna().any().any())

True
True

In [121]:
te_before_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']] = te_before_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']].fillna(0)
te_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']] = te_2024[['Injury', 'Wed', 'Thu', 'Fri', 'Game Status']].fillna(0)

In [122]:
print(te_before_2024.isna().any().any())
print(te_2024.isna().any().any())

False
False

In [123]:
duplicates = te_before_2024[te_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False)]
print(duplicates)
duplicates = te_2024[te_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False)]
duplicates

     week    player_name  opponent_team  team  year  points depth_team  \
399     2  George Kittle              7     1  2023     6.0          1
400     2  George Kittle              7     1  2023     6.0          1
745     2   Mark Andrews             14     6  2023    15.5          3
746     2   Mark Andrews             14     6  2023    15.5          3

     prev_completions  prev_attempts  prev_passing_yards  ...  \
399                 0              0                 0.0  ...
400                 0              0                 0.0  ...
745                 0              0                 0.0  ...
746                 0              0                 0.0  ...

     cum_air_yards_share  cum_wopr  cum_points   age  len_with_team  Injury  \
399             0.134783  0.415776         4.9  29.0            7.0    16.0
400             0.134783  0.415776         4.9  29.0            7.0    13.0
745             0.000000  0.000000         0.0  27.0            6.0     7.0
746             0.000000  0.000000         0.0  27.0            6.0    10.0

     Wed  Thu  Fri  Game Status
399  1.0  1.0  1.0          1.0
400  1.0  1.0  1.0          1.0
745  2.0  2.0  1.0          2.0
746  2.0  1.0  1.0          2.0

[4 rows x 93 columns]

,week,player_name,opponent_team,team,year,points,depth_team,prev_completions,prev_attempts,prev_passing_yards,...,cum_air_yards_share,cum_wopr,cum_points,age,len_with_team,Injury,Wed,Thu,Fri,Game Status
261,2,Dalton Schultz,19,15,2024,4.1,1,0,0,0.0,...,0.052419,0.181855,4.6,28.0,2.0,10,3,3,1,1
262,2,Dalton Schultz,19,15,2024,4.1,1,0,0,0.0,...,0.052419,0.181855,4.6,28.0,2.0,69,2,2,1,1
1119,2,Zach Ertz,29,20,2024,10.2,1,0,0,0.0,...,0.224000,0.406800,5.8,33.0,1.0,66,3,4,4,1
1120,2,Zach Ertz,29,20,2024,10.2,1,0,0,0.0,...,0.224000,0.406800,5.8,33.0,1.0,12,3,2,1,1
1121,3,Zach Ertz,14,20,2024,8.8,1,0,0,0.0,...,0.642033,0.906319,16.0,33.0,1.0,66,2,4,4,1
1122,3,Zach Ertz,14,20,2024,8.8,1,0,0,0.0,...,0.642033,0.906319,16.0,33.0,1.0,12,3,1,1,1

In [124]:
te_before_2024.drop(index=[400, 746], inplace=True)
te_2024.drop(index=[262, 1119, 1121], inplace=True)

In [125]:
print(te_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False).any())
print(te_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False).any())

False
False

### Merge te with sal

In [126]:
te_before_2024 = te_before_2024.merge(te_sal, on=['player_name'], how='left')
te_2024 = te_2024.merge(te_sal, on=['player_name'], how='left')

In [127]:
print(te_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False).any())
print(te_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False).any())

False
False

In [128]:
print(te_before_2024.isna().any().any())
print(te_2024.isna().any().any())

True
True

In [129]:
cols = ['Total Value', 'APY', 'Total Guaranteed', 'Avg. Guarantee/Year', '% Guaranteed']
for df in [te_before_2024, te_2024]:
    for col in cols:
        df[col].fillna(df[col].mean(), inplace=True)

In [130]:
print(te_before_2024.isna().any().any())
print(te_2024.isna().any().any())

False
False

### Merge with previous data

In [131]:
te_before_2024 = te_before_2024.merge(f_before_2024, on=['year', 'week', 'team'], how='left')
te_2024 = te_2024.merge(f_2024, on=['year', 'week', 'team'], how='left')

In [132]:
print(te_before_2024.isna().any().any())
print(te_2024.isna().any().any())

False
False

In [133]:
print(te_before_2024.duplicated(subset=['year', 'player_name', 'week', 'team'], keep=False).any())
print(te_2024.duplicated(subset=['player_name', 'week', 'team'], keep=False).any())

False
False

### Append te to final_dfs

In [134]:
final_dfs.append([te_before_2024, te_2024])

### Preprocess and Save final_dfs

In [135]:
for col, val in final_dfs[0][0].iloc[23].items():
    print(col, val, type(val))

week 12 <class 'numpy.int32'>
player_name Bailey Zappe <class 'str'>
opponent_team 29 <class 'numpy.int64'>
team 30 <class 'numpy.int64'>
year 2023 <class 'numpy.int64'>
points 0.16 <class 'numpy.float32'>
depth_team 2 <class 'str'>
prev_completions 65 <class 'numpy.int64'>
prev_attempts 92 <class 'numpy.int64'>
prev_passing_yards 781.0 <class 'numpy.float64'>
prev_passing_tds 5 <class 'numpy.int64'>
prev_interceptions 3.0 <class 'numpy.float64'>
prev_sacks 6.0 <class 'numpy.float64'>
prev_sack_yards 40.0 <class 'numpy.float64'>
prev_sack_fumbles 2 <class 'numpy.int64'>
prev_sack_fumbles_lost 2 <class 'numpy.int64'>
prev_passing_air_yards 624.0 <class 'numpy.float64'>
prev_passing_yards_after_catch 384.0 <class 'numpy.float64'>
prev_passing_first_downs 37.0 <class 'numpy.float64'>
prev_passing_epa 7.6850175857543945 <class 'numpy.float64'>
prev_passing_2pt_conversions 0 <class 'numpy.int64'>
prev_pacr 4.978248596191406 <class 'numpy.float64'>
prev_dakota 0.4876483976840973 <class 'numpy.float64'>
prev_carries 10 <class 'numpy.int64'>
prev_rushing_yards 0.0 <class 'numpy.float64'>
prev_rushing_tds 0 <class 'numpy.int64'>
prev_rushing_fumbles 2.0 <class 'numpy.float64'>
prev_rushing_fumbles_lost 1.0 <class 'numpy.float64'>
prev_rushing_first_downs 0.0 <class 'numpy.float64'>
prev_rushing_epa -6.099722862243652 <class 'numpy.float64'>
prev_rushing_2pt_conversions 0 <class 'numpy.int64'>
prev_receptions 1 <class 'numpy.int64'>
prev_targets 1 <class 'numpy.int64'>
prev_receiving_yards -6.0 <class 'numpy.float64'>
prev_receiving_tds 0 <class 'numpy.int64'>
prev_receiving_fumbles 0.0 <class 'numpy.float64'>
prev_receiving_fumbles_lost 0.0 <class 'numpy.float64'>
prev_receiving_air_yards -8.0 <class 'numpy.float64'>
prev_receiving_yards_after_catch 2.0 <class 'numpy.float64'>
prev_receiving_first_downs 0.0 <class 'numpy.float64'>
prev_receiving_epa -1.2425923347473145 <class 'numpy.float64'>
prev_receiving_2pt_conversions 0 <class 'numpy.int64'>
prev_racr 0.0 <class 'numpy.float64'>
prev_target_share 0.032258063554763794 <class 'numpy.float64'>
prev_air_yards_share -0.04371584579348564 <class 'numpy.float64'>
prev_wopr 0.01778600364923477 <class 'numpy.float64'>
cum_completions 10 <class 'numpy.int64'>
cum_attempts 25 <class 'numpy.int64'>
cum_passing_yards 104 <class 'numpy.int64'>
cum_passing_tds 0 <class 'numpy.int64'>
cum_interceptions 1 <class 'numpy.int64'>
cum_sacks 1 <class 'numpy.int64'>
cum_sack_yards 7 <class 'numpy.int64'>
cum_sack_fumbles 0 <class 'numpy.int64'>
cum_sack_fumbles_lost 0 <class 'numpy.int64'>
cum_passing_air_yards 301 <class 'numpy.int64'>
cum_passing_yards_after_catch 37 <class 'numpy.int64'>
cum_passing_first_downs 3 <class 'numpy.int64'>
cum_passing_epa -11.39172476530075 <class 'numpy.float64'>
cum_passing_2pt_conversions 0 <class 'numpy.int64'>
cum_pacr 1.1529072970151901 <class 'numpy.float64'>
cum_dakota -0.1860496550798416 <class 'numpy.float64'>
cum_carries 0 <class 'numpy.int64'>
cum_rushing_yards 0 <class 'numpy.int64'>
cum_rushing_tds 0 <class 'numpy.int64'>
cum_rushing_fumbles 0 <class 'numpy.int64'>
cum_rushing_fumbles_lost 0 <class 'numpy.int64'>
cum_rushing_first_downs 0 <class 'numpy.int64'>
cum_rushing_epa 0.0 <class 'numpy.float64'>
cum_rushing_2pt_conversions 0 <class 'numpy.int64'>
cum_receptions 0 <class 'numpy.int64'>
cum_targets 0 <class 'numpy.int64'>
cum_receiving_yards 0 <class 'numpy.int64'>
cum_receiving_tds 0 <class 'numpy.int64'>
cum_receiving_fumbles 0 <class 'numpy.int64'>
cum_receiving_fumbles_lost 0 <class 'numpy.int64'>
cum_receiving_air_yards 0 <class 'numpy.int64'>
cum_receiving_yards_after_catch 0 <class 'numpy.int64'>
cum_receiving_first_downs 0 <class 'numpy.int64'>
cum_receiving_epa 0.0 <class 'numpy.float64'>
cum_receiving_2pt_conversions 0 <class 'numpy.int64'>
cum_racr 0 <class 'numpy.int64'>
cum_target_share 0.0 <class 'numpy.float64'>
cum_air_yards_share 0.0 <class 'numpy.float64'>
cum_wopr 0.0 <class 'numpy.float64'>
cum_points 2.159999966621399 <class 'numpy.float64'>
age 24.0 <class 'numpy.float64'>
len_with_team 2.0 <class 'numpy.float64'>
Injury 0.0 <class 'numpy.float64'>
Wed 0.0 <class 'numpy.float64'>
Thu 0.0 <class 'numpy.float64'>
Fri 0.0 <class 'numpy.float64'>
Game Status 0.0 <class 'numpy.float64'>
Total Value 1100000.0 <class 'numpy.float64'>
APY 1100000.0 <class 'numpy.float64'>
Total Guaranteed 396000.0 <class 'numpy.float64'>
Avg. Guarantee/Year 396000.0 <class 'numpy.float64'>
% Guaranteed 0.36 <class 'numpy.float64'>
G-season 17 <class 'str'>
W-season 8 <class 'str'>
L-season 9 <class 'str'>
T-season 0 <class 'str'>
G-w/team 387 <class 'str'>
W-w/team 266 <class 'str'>
L-w/team 121 <class 'str'>
T-w/team 0 <class 'str'>
G-career 467 <class 'str'>
W-career 302 <class 'str'>
L-career 165 <class 'str'>
T-career 0 <class 'str'>
G plyf-playoffs 0 <class 'str'>
W plyf-playoffs 0 <class 'str'>
L plyf-playoffs 0 <class 'str'>
G plyf-w/team 42 <class 'str'>
W plyf-w/team 30 <class 'str'>
L plyf-w/team 12 <class 'str'>
G plyf-career 44 <class 'str'>
W plyf-career 31 <class 'str'>
L plyf-career 13 <class 'str'>
Remark 0 <class 'numpy.int64'>
w/same_team 1.0 <class 'numpy.float64'>
Gms-fds 17 <class 'str'>
Rush-fds 98 <class 'str'>
Pass-fds 166 <class 'str'>
Pen-fds 24 <class 'str'>
Pct-tde 34.9 <class 'str'>
Pct-fde 38.5 <class 'str'>
gameday 35 <class 'numpy.int32'>
weekday 3 <class 'numpy.int32'>
gametime 2 <class 'numpy.int32'>
away_team 30 <class 'numpy.int64'>
home_team 29 <class 'numpy.int64'>
away_moneyline -218.0 <class 'numpy.float64'>
home_moneyline 180.0 <class 'numpy.float64'>
spread_line -4.5 <class 'numpy.float64'>
away_spread_odds -108.0 <class 'numpy.float64'>
home_spread_odds -112.0 <class 'numpy.float64'>
total_line 36.5 <class 'numpy.float64'>
under_odds -105.0 <class 'numpy.float64'>
over_odds -115.0 <class 'numpy.float64'>
div_game 0 <class 'numpy.int64'>
roof 3 <class 'numpy.int32'>
surface 2 <class 'numpy.int32'>
temp 43.0 <class 'numpy.float64'>
wind 6.0 <class 'numpy.float64'>
referee 13 <class 'numpy.int32'>
stadium 20 <class 'numpy.int32'>
bye_week 11 <class 'numpy.int64'>
oline_rank 25 <class 'numpy.int64'>
dline_rank 7 <class 'numpy.int64'>

In [136]:
from preprocess import preprocess_dataframe
for i in range(len(final_dfs)):
    final_dfs[i][0] = preprocess_dataframe(final_dfs[i][0])
    final_dfs[i][1] = preprocess_dataframe(final_dfs[i][1])

In [137]:
for col, val in final_dfs[0][0].iloc[23].items():
    print(col, val)

year 0.0
points 0.16
prev_completions -0.9141283317167606
prev_attempts -0.947976149744406
prev_passing_yards -0.8992600388111104
prev_passing_tds -0.800181492869388
prev_interceptions -0.893492202458584
prev_sacks -0.9871501679287334
prev_sack_yards -0.962949869315335
prev_sack_fumbles -0.7359517093892112
prev_sack_fumbles_lost -0.17260037269321318
prev_passing_air_yards -0.9795709726373862
prev_passing_yards_after_catch -0.8634598345032628
prev_passing_first_downs -0.8846139074539183
prev_passing_epa -0.3096376401280647
prev_passing_2pt_conversions -0.8224942972211472
prev_pacr -0.9038745362517099
prev_dakota -0.7307191896664854
prev_carries -0.7476518727372604
prev_rushing_yards -0.7077520171793833
prev_rushing_tds -0.6515576209072331
prev_rushing_fumbles -0.3818438960776862
prev_rushing_fumbles_lost 0.04976585952752262
prev_rushing_first_downs -0.7724601777420389
prev_rushing_epa -0.543025611372683
prev_rushing_2pt_conversions -0.5112143971808956
prev_receptions 1.8659573845409616
prev_targets 1.4560591157246834
prev_receiving_yards -2.4124518303876012
prev_receiving_tds -0.13353130424166998
prev_receiving_fumbles 0.0
prev_receiving_fumbles_lost 0.0
prev_receiving_air_yards -2.123176377151699
prev_receiving_yards_after_catch 0.3304963384539093
prev_receiving_first_downs -0.16427570345801806
prev_receiving_epa -1.3968434345359737
prev_receiving_2pt_conversions -0.2423481216259813
prev_racr -0.16342164997100433
prev_target_share 1.446296153011564
prev_air_yards_share -2.542587552226336
prev_wopr 0.23053495232387164
cum_completions -0.9678594820197894
cum_attempts -0.9218209732149591
cum_passing_yards -0.9442118647933023
cum_passing_tds -0.9173236314048621
cum_interceptions -0.7632321048449131
cum_sacks -0.9682861352729156
cum_sack_yards -0.941913948577454
cum_sack_fumbles -0.8456684134910695
cum_sack_fumbles_lost -0.7033989816183137
cum_passing_air_yards -0.8327894461159688
cum_passing_yards_after_catch -0.9483296661281947
cum_passing_first_downs -0.9674872675803434
cum_passing_epa -0.43960948865893806
cum_passing_2pt_conversions -0.5148912530021077
cum_pacr -0.8771548524590199
cum_dakota -1.0937353042822517
cum_carries -0.8345931124638037
cum_rushing_yards -0.7065545827724451
cum_rushing_tds -0.5082946143643339
cum_rushing_fumbles -0.670721405511158
cum_rushing_fumbles_lost -0.48343128338744884
cum_rushing_first_downs -0.7143771197752835
cum_rushing_epa -0.12326735679691272
cum_rushing_2pt_conversions -0.2717317709358858
cum_receptions -0.29253794097461483
cum_targets -0.29253794097461483
cum_receiving_yards 0.058494953090500505
cum_receiving_tds 0.0
cum_receiving_fumbles 0.0
cum_receiving_fumbles_lost 0.0
cum_receiving_air_yards 0.2550159165091608
cum_receiving_yards_after_catch -0.1616627162749725
cum_receiving_first_downs -0.10870528503972879
cum_receiving_epa 0.17126796356717472
cum_receiving_2pt_conversions -0.10870528503972879
cum_racr 0.0
cum_target_share -0.27357825870327057
cum_air_yards_share 0.23011345119088827
cum_wopr -0.26854273122697475
cum_points -0.9463028103372316
age -0.7757929753893871
len_with_team -0.4805761829992655
Total Value -0.8941051548612139
APY -1.0517520595055876
Total Guaranteed -0.9510832698460298
Avg. Guarantee/Year -1.0672535988031004
% Guaranteed -0.4608131331705186
G-season 17
W-season 8
L-season 9
T-season 0
G-w/team 387
W-w/team 266
L-w/team 121
T-w/team 0
G-career 467
W-career 302
L-career 165
T-career 0
G plyf-playoffs 0
W plyf-playoffs 0
L plyf-playoffs 0
G plyf-w/team 42
W plyf-w/team 30
L plyf-w/team 12
G plyf-career 44
W plyf-career 31
L plyf-career 13
w/same_team 0.4491707759470916
Gms-fds 17
Rush-fds 98
Pass-fds 166
Pen-fds 24
Pct-tde 34.9
Pct-fde 38.5
away_moneyline -0.9370177761312702
home_moneyline 0.9236162926978552
spread_line -1.0831815648774992
away_spread_odds -0.17239984888525467
home_spread_odds -0.2608599956009201
total_line -1.5032240423638825
under_odds 0.35279728477542266
over_odds -2.160361743970318
roof 3
surface 2
temp 0.4013077106199926
wind 0.28228494483822925
oline_rank 0.921825622794484
dline_rank -1.001277931134549
team_0 0
team_1 0
team_2 0
team_3 0
team_4 0
team_5 0
team_6 0
team_7 0
team_8 0
team_9 0
team_10 0
team_11 0
team_12 0
team_13 0
team_14 0
team_15 0
team_16 0
team_17 0
team_18 0
team_19 0
team_20 0
team_21 0
team_22 0
team_23 0
team_24 0
team_25 0
team_26 0
team_27 0
team_28 0
team_29 0
team_30 1
team_31 0
home_team_0 0
home_team_1 0
home_team_2 0
home_team_3 0
home_team_4 0
home_team_5 0
home_team_6 0
home_team_7 0
home_team_8 0
home_team_9 0
home_team_10 0
home_team_11 0
home_team_12 0
home_team_13 0
home_team_14 0
home_team_15 0
home_team_16 0
home_team_17 0
home_team_18 0
home_team_19 0
home_team_20 0
home_team_21 0
home_team_22 0
home_team_23 0
home_team_24 0
home_team_25 0
home_team_26 0
home_team_27 0
home_team_28 0
home_team_29 1
home_team_30 0
home_team_31 0
opponent_team_0 0
opponent_team_1 0
opponent_team_2 0
opponent_team_3 0
opponent_team_4 0
opponent_team_5 0
opponent_team_6 0
opponent_team_7 0
opponent_team_8 0
opponent_team_9 0
opponent_team_10 0
opponent_team_11 0
opponent_team_12 0
opponent_team_13 0
opponent_team_14 0
opponent_team_15 0
opponent_team_16 0
opponent_team_17 0
opponent_team_18 0
opponent_team_19 0
opponent_team_20 0
opponent_team_21 0
opponent_team_22 0
opponent_team_23 0
opponent_team_24 0
opponent_team_25 0
opponent_team_26 0
opponent_team_27 0
opponent_team_28 0
opponent_team_29 1
opponent_team_30 0
opponent_team_31 0
away_team_0 0
away_team_1 0
away_team_2 0
away_team_3 0
away_team_4 0
away_team_5 0
away_team_6 0
away_team_7 0
away_team_8 0
away_team_9 0
away_team_10 0
away_team_11 0
away_team_12 0
away_team_13 0
away_team_14 0
away_team_15 0
away_team_16 0
away_team_17 0
away_team_18 0
away_team_19 0
away_team_20 0
away_team_21 0
away_team_22 0
away_team_23 0
away_team_24 0
away_team_25 0
away_team_26 0
away_team_27 0
away_team_28 0
away_team_29 0
away_team_30 1
away_team_31 0
bye_week_5 0
bye_week_6 0
bye_week_7 0
bye_week_9 0
bye_week_10 0
bye_week_11 1
bye_week_13 0
bye_week_14 0
Injury_0.0 1
Injury_1.0 0
Injury_2.0 0
Injury_3.0 0
Injury_6.0 0
Injury_8.0 0
Injury_10.0 0
Injury_12.0 0
Injury_13.0 0
Injury_14.0 0
Injury_15.0 0
Injury_16.0 0
Injury_17.0 0
Injury_18.0 0
Injury_20.0 0
Injury_21.0 0
Injury_22.0 0
Injury_23.0 0
Injury_24.0 0
Injury_25.0 0
Injury_26.0 0
Injury_27.0 0
Injury_34.0 0
Injury_39.0 0
Injury_40.0 0
Injury_41.0 0
Injury_42.0 0
Injury_48.0 0
Injury_51.0 0
Injury_54.0 0
Injury_57.0 0
Injury_58.0 0
Injury_59.0 0
Injury_60.0 0
Injury_62.0 0
Wed_0.0 1
Wed_1.0 0
Wed_2.0 0
Wed_3.0 0
Wed_4.0 0
Thu_0.0 1
Thu_1.0 0
Thu_2.0 0
Thu_3.0 0
Thu_4.0 0
Fri_0.0 1
Fri_1.0 0
Fri_2.0 0
Fri_3.0 0
Fri_4.0 0
Game Status_0.0 1
Game Status_1.0 0
Game Status_2.0 0
div_game_0 1
div_game_1 0
Remark_0 1
Remark_2 0
Remark_3 0
Remark_4 0
depth_team_1 0
depth_team_2 1
depth_team_3 0
player_name Bailey Zappe
week 12
stadium 20
referee 13
gameday 35
weekday 3
gametime 2

In [138]:
import pickle
with open('pickles/dataframes.pickle', 'wb') as f:
    pickle.dump(final_dfs, f)